Repository theohbrothers/test-dockerimagevariants, pull requests merged in 2023-09, with the labels that each got.

#6 Enhancement: Bump v0.2 variants to v0.2.1
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.2.1-alpine-3.15/Dockerfile
Labels: enhancement

#5 Enhancement: Bump v0.3 variants to v0.3.1
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.3.1-alpine-3.15/Dockerfile
Labels: enhancement

#8 Enhancement: Bump v0.2 variants to v0.2.2
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.2.2-alpine-3.15/Dockerfile
Labels: enhancement

#9 Enhancement: Bump v0.2 variants to v0.2.3
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.2.3-alpine-3.15/Dockerfile
Labels: enhancement

#10 Enhancement: Bump v0.2 variants to v0.2.4
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.2.4-alpine-3.15/Dockerfile
Labels: enhancement

#11 Enhancement: Bump v0.2 variants to v0.2.5
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.2.5-alpine-3.15/Dockerfile
Labels: enhancement

#7 Enhancement: Bump v0.3 variants to v0.3.2
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.3.2-alpine-3.15/Dockerfile
Labels: enhancement

#13 Enhancement: Bump v0.2 variants to v0.2.6
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.2.6-alpine-3.15/Dockerfile
Labels: enhancement

#12 Enhancement: Bump v0.3 variants to v0.3.3
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.3.3-alpine-3.15/Dockerfile
Labels: enhancement

#15 Enhancement: Bump v0.2 variants to v0.2.7
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.2.7-alpine-3.15/Dockerfile
Labels: enhancement

#4 Enhancement: Add v0.4.0 variants
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.4.0-alpine-3.15/Dockerfile
Labels: enhancement

#17 Enhancement: Bump v0.4 variants to v0.4.1
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.4.1-alpine-3.15/Dockerfile
Labels: enhancement

#14 Enhancement: Bump v0.3 variants to v0.3.4
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.3.4-alpine-3.15/Dockerfile
Labels: enhancement

#16 Enhancement: Bump v0.2 variants to v0.2.8
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.2.8-alpine-3.15/Dockerfile
Labels: enhancement

#18 Enhancement: Bump v0.4 variants to v0.4.2
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.4.2-alpine-3.15/Dockerfile
Labels: enhancement

#19 Enhancement: Bump v0.3 variants to v0.3.5
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.3.5-alpine-3.15/Dockerfile
Labels: enhancement

#20 Enhancement: Bump v0.2 variants to v0.2.9
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.2.9-alpine-3.15/Dockerfile
Labels: enhancement

#21 Enhancement: Bump v0.4 variants to v0.4.3
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.4.3-alpine-3.15/Dockerfile
Labels: enhancement

#22 Fix (ci): Use `actions/checkout@v1` to fetch all tags in `cron` job
  .github/workflows/cron.yml
  generate/templates/.github/workflows/cron.yml.ps1
Labels: fix

#23 Enhancement: Bump v0.4 variants to v0.4.4
  .github/workflows/ci-master-pr.yml
  README.md
  Update-Versions.ps1
  generate/definitions/versions.json
  variants/v0.4.4-alpine-3.15/Dockerfile
Labels: enhancement

#24 Enhancement: Bump v0.4 variants to v0.4.5
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.4.5-alpine-3.15/Dockerfile
Labels: enhancement

#25 Enhancement: Bump v0.3 variants to v0.3.6
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.3.6-alpine-3.15/Dockerfile
Labels: enhancement

#26 Enhancement: Bump v0.2 variants to v0.2.10
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.2.10-alpine-3.15/Dockerfile
Labels: enhancement

#27 Enhancement: Bump v0.4 variants to v0.4.6
  .github/workflows/ci-master-pr.yml
  README.md
  Update-Versions.ps1
  generate/definitions/versions.json
  variants/v0.4.6-alpine-3.15/Dockerfile
Labels: enhancement

#28 Enhancement: Bump v0.3 variants to v0.3.7
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.3.7-alpine-3.15/Dockerfile
Labels: enhancement

#30 Enhancement: Bump v0.4 variants to v0.4.7
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.4.7-alpine-3.15/Dockerfile
Labels: enhancement

#31 Enhancement: Bump v0.3 variants to v0.3.8
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.3.8-alpine-3.15/Dockerfile
Labels: enhancement

#32 Enhancement: Bump v0.3 variants to v0.3.9
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.3.9-alpine-3.15/Dockerfile
Labels: enhancement

#29 Enhancement: Bump v0.2 variants to v0.2.11
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.2.11-alpine-3.15/Dockerfile
Labels: enhancement

#33 Enhancement: Bump v0.4 variants to v0.4.8
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.4.8-alpine-3.15/Dockerfile
Labels: enhancement

#34 Enhancement: Bump v0.3 variants to v0.3.10
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.3.10-alpine-3.15/Dockerfile
Labels: enhancement

#35 Enhancement: Bump v0.2 variants to v0.2.12
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.2.12-alpine-3.15/Dockerfile
Labels: enhancement

#36 Enhancement: Bump v0.4 variants to v0.4.9
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.4.9-alpine-3.15/Dockerfile
Labels: enhancement

#37 Enhancement: Bump v0.3 variants to v0.3.11
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.3.11-alpine-3.15/Dockerfile
Labels: enhancement

#38 Enhancement: Bump v0.2 variants to v0.2.13
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.2.13-alpine-3.15/Dockerfile
Labels: enhancement

#39 Enhancement: Bump v0.4 variants to v0.4.10
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.4.10-alpine-3.15/Dockerfile
Labels: enhancement

#40 Enhancement: Bump coolpackage 0.4 variants to 0.4.11
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.4.11-alpine-3.15/Dockerfile
Labels: enhancement

#41 Enhancement: Bump coolpackage 0.4 variants to 0.4.12
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.4.12-alpine-3.15/Dockerfile
Labels: enhancement

#42 Enhancement: Bump coolpackage 0.3 variants to 0.3.12
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.3.12-alpine-3.15/Dockerfile
Labels: enhancement

#43 Enhancement: Bump coolpackage 0.2 variants to 0.2.14
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.2.14-alpine-3.15/Dockerfile
Labels: enhancement

#44 Enhancement: Bump coolpackage 0.4 variants to 0.4.13
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.4.13-alpine-3.15/Dockerfile
Labels: enhancement

#45 Enhancement: Bump coolpackage 0.3 variants to 0.3.12
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
Labels: enhancement

#46 Enhancement: Bump coolpackage 0.4 variants to 0.4.15
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.4.15-alpine-3.15/Dockerfile
Labels: enhancement

#47 Enhancement: Bump coolpackage 0.3 variants to 0.3.15
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.3.15-alpine-3.15/Dockerfile
Labels: enhancement

#49 Enhancement: Bump coolpackage 0.4 variants to 0.4.16
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.4.16-alpine-3.15/Dockerfile
Labels: enhancement

#50 Enhancement: Bump coolpackage 0.3 variants to 0.3.16
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.3.16-alpine-3.15/Dockerfile
Labels: enhancement

#51 Enhancement: Bump coolpackage 0.2 variants to 0.2.16
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.2.16-alpine-3.15/Dockerfile
Labels: enhancement

#52 Enhancement: Bump coolpackage 0.4 variants to 0.4.17
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.4.17-alpine-3.15/Dockerfile
Labels: enhancement

#53 Enhancement: Bump coolpackage 0.3 variants to 0.3.17
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.3.17-alpine-3.15/Dockerfile
Labels: enhancement

#54 Enhancement: Bump coolpackage 0.2 variants to 0.2.17
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v0.2.17-alpine-3.15/Dockerfile
Labels: enhancement

#55 Feature: Add `curl` variants
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/VARIANTS.ps1
  generate/templates/Dockerfile.ps1
  variants/v0.1.0-curl-alpine-3.15/Dockerfile
  variants/v0.2.17-curl-alpine-3.15/Dockerfile
  variants/v0.3.17-curl-alpine-3.15/Dockerfile
  variants/v0.4.17-curl-alpine-3.15/Dockerfile
Labels: feature

#57 Enhancement (ci): Add support for incremental variants
  .github/workflows/ci-master-pr.yml
  generate/templates/.github/workflows/ci-master-pr.yml.ps1
Labels: enhancement

#58 Style (ci): Add newline after job
  .github/workflows/ci-master-pr.yml
  generate/templates/.github/workflows/ci-master-pr.yml.ps1
Labels: style

#60 Refactor (ci): Use a `job_group_key` to group jobs
  generate/definitions/VARIANTS.ps1
  generate/templates/.github/workflows/ci-master-pr.yml.ps1
Labels: refactor

#61 Refactor (ci): Bump `test-nogitdiff` job image
  .github/workflows/ci-master-pr.yml
  generate/templates/.github/workflows/ci-master-pr.yml.ps1
Labels: refactor
